version: "3.9"
services:
  postgresql:
    image: postgres:17-alpine
    platform: linux/arm64/v8
    container_name: templ-db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./ops/multi-db.sh:/docker-entrypoint-initdb.d/multi-db.sh
      - templ_pg_data:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: |
        ${DB_NAME}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  templ_pg_data: