// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createStmt, err = db.PrepareContext(ctx, create); err != nil {
		return nil, fmt.Errorf("error preparing query Create: %w", err)
	}
	if q.deleteStmt, err = db.PrepareContext(ctx, delete); err != nil {
		return nil, fmt.Errorf("error preparing query Delete: %w", err)
	}
	if q.existStmt, err = db.PrepareContext(ctx, exist); err != nil {
		return nil, fmt.Errorf("error preparing query Exist: %w", err)
	}
	if q.findOneStmt, err = db.PrepareContext(ctx, findOne); err != nil {
		return nil, fmt.Errorf("error preparing query FindOne: %w", err)
	}
	if q.updateOneStmt, err = db.PrepareContext(ctx, updateOne); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOne: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createStmt != nil {
		if cerr := q.createStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStmt: %w", cerr)
		}
	}
	if q.deleteStmt != nil {
		if cerr := q.deleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStmt: %w", cerr)
		}
	}
	if q.existStmt != nil {
		if cerr := q.existStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existStmt: %w", cerr)
		}
	}
	if q.findOneStmt != nil {
		if cerr := q.findOneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findOneStmt: %w", cerr)
		}
	}
	if q.updateOneStmt != nil {
		if cerr := q.updateOneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOneStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db            DBTX
	tx            *sql.Tx
	createStmt    *sql.Stmt
	deleteStmt    *sql.Stmt
	existStmt     *sql.Stmt
	findOneStmt   *sql.Stmt
	updateOneStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:            tx,
		tx:            tx,
		createStmt:    q.createStmt,
		deleteStmt:    q.deleteStmt,
		existStmt:     q.existStmt,
		findOneStmt:   q.findOneStmt,
		updateOneStmt: q.updateOneStmt,
	}
}
