// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const findOne = `-- name: FindOne :one
SELECT id, name, email, password, created_at
FROM users
WHERE id = $1
`

func (q *Queries) FindOne(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.findOneStmt, findOne, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
