FROM golang:1.23-alpine

RUN apk add build-base

RUN go install github.com/bufbuild/buf/cmd/buf@v1.32.0 && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0 && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0 && \
    go install github.com/swaggo/swag/cmd/swag@v1.16.4
